language: php

php:
  - 5.5
  - 5.6

env:
  - DOCTRINE_VERSION=2.3.* ES_VERSION=3.*
  - DOCTRINE_VERSION=2.4.* ES_VERSION=3.*
  - DOCTRINE_VERSION=2.5.*@dev ES_VERSION=3.*

before_script:
  - composer self-update
  - composer require doctrine/dbal:${DOCTRINE_VERSION} --dev --prefer-source
  - composer require prooph/event-store:${ES_VERSION} --dev --prefer-source
  - composer install --dev --prefer-source

script:
  - php ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.doctrine-$DOCTRINE_VERSION.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_script:
  - php vendor/bin/coveralls -v
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
